spring:
  application:
    name: products
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false
server:
  port: 8081
  servlet:
    context-path: /e-auction/api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring.cloud.consul.enabled: false

